TWITTER_AUTHORIZATION_HEADER    = "Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA"
TWITTER_ACTIVATE_EP             = "https://api.twitter.com/1.1/guest/activate.json"
TWITTER_FLOWTOKEN_EP            = "https://twitter.com/i/api/1.1/onboarding/task.json?flow_name=signup"
TWITTER_BEGINVERIFICATION_EP    = "https://twitter.com/i/api/1.1/onboarding/begin_verification.json"
TWITTER_TASK_EP                 = "https://twitter.com/i/api/1.1/onboarding/task.json"
TWITTER_PASSWORDSTRENGTH_EP     = "https://twitter.com/i/api/1.1/account/password_strength.json"
TWITTER_UPLOAD_EP               = "https://upload.twitter.com/1.1/media/upload.json"
TWITTER_UPDATEPFP_EP            = "https://twitter.com/i/api/1.1/account/update_profile_image.json"
TWITTER_UPDATEBANNER_EP         = "https://twitter.com/i/api/1.1/account/update_profile_banner.json"
TWITTER_CREATETWEET_EP          = "https://twitter.com/i/api/graphql/JPjstjvQ-KCFmAR997gVPQ/CreateTweet"
TWITTER_UPDATEPROFILE_EP        = "https://twitter.com/i/api/1.1/account/update_profile.json"
TWITTER_EMAIL_EXISTS_EP         = "https://twitter.com/i/api/i/users/email_available.json"